-- MCR coffee_source backfill — generated, NOT executed. Review before applying.
-- Requires 20260621000001_coffee_source_supplier (supplier_id col) applied first.
BEGIN;

-- 1. New Hawaiian farm suppliers
INSERT INTO supplier (supplier_id, supplier, supplier_category, company_id, is_active) VALUES ('mcr-sup-aloha-farms', 'Aloha Farms', 'Green Coffee', '9ShiyDAXhV', true) ON CONFLICT (supplier_id) DO NOTHING;
INSERT INTO supplier (supplier_id, supplier, supplier_category, company_id, is_active) VALUES ('mcr-sup-aloha-hills', 'Aloha Hills', 'Green Coffee', '9ShiyDAXhV', true) ON CONFLICT (supplier_id) DO NOTHING;
INSERT INTO supplier (supplier_id, supplier, supplier_category, company_id, is_active) VALUES ('mcr-sup-generations-kona', 'Generations Kona', 'Green Coffee', '9ShiyDAXhV', true) ON CONFLICT (supplier_id) DO NOTHING;
INSERT INTO supplier (supplier_id, supplier, supplier_category, company_id, is_active) VALUES ('mcr-sup-kau-coffee-mill', 'Kau Coffee Mill', 'Green Coffee', '9ShiyDAXhV', true) ON CONFLICT (supplier_id) DO NOTHING;
INSERT INTO supplier (supplier_id, supplier, supplier_category, company_id, is_active) VALUES ('mcr-sup-kona-coffee-company', 'Kona Coffee Company', 'Green Coffee', '9ShiyDAXhV', true) ON CONFLICT (supplier_id) DO NOTHING;
INSERT INTO supplier (supplier_id, supplier, supplier_category, company_id, is_active) VALUES ('mcr-sup-mahi-pono-farms', 'Mahi Pono Farms', 'Green Coffee', '9ShiyDAXhV', true) ON CONFLICT (supplier_id) DO NOTHING;
INSERT INTO supplier (supplier_id, supplier, supplier_category, company_id, is_active) VALUES ('mcr-sup-maui-grown-coffee', 'Maui Grown Coffee', 'Green Coffee', '9ShiyDAXhV', true) ON CONFLICT (supplier_id) DO NOTHING;

-- 2. coffee_source backfill
UPDATE coffee_source SET country_of_origin='Brazil', region='Alta Mogiana', process=NULL, farm=NULL, grade_quality='SS', grade_classification='FC', grade_screen='17/18', grade_prep=NULL, grade_label='SS FC 17/18', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='e498f99c-8cbb-4ff2-bb46-521f52eae9a4';
UPDATE coffee_source SET country_of_origin='Brazil', region='Mogiana', process=NULL, farm=NULL, grade_quality='SS', grade_classification='FC', grade_screen=NULL, grade_prep=NULL, grade_label='SS FC', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_e6cac7ee284067a7';
UPDATE coffee_source SET country_of_origin='Brazil', region='Mogiana', process=NULL, farm=NULL, grade_quality='SS', grade_classification='FC', grade_screen='15/16', grade_prep=NULL, grade_label='SS FC 15/16', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_5de796c028876030';
UPDATE coffee_source SET country_of_origin='Brazil', region='Mogiana', process=NULL, farm=NULL, grade_quality='SS', grade_classification='FC', grade_screen=NULL, grade_prep=NULL, grade_label='SS FC', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_d7988f5e334bbb0f';
UPDATE coffee_source SET country_of_origin='Brazil', region='Mogiana', process=NULL, farm=NULL, grade_quality='SS', grade_classification='FC', grade_screen='17/18', grade_prep=NULL, grade_label='SS FC 17/18', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_81f73985aac71db7';
UPDATE coffee_source SET country_of_origin='Brazil', region=NULL, process=NULL, farm=NULL, grade_quality='SS', grade_classification='FC', grade_screen='15/16', grade_prep=NULL, grade_label='SS FC 15/16', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='b70fd2e2-bf3e-4cbe-a9f0-5f61b6fb51e5';
UPDATE coffee_source SET country_of_origin='Brazil', region='Sul de Minas', process=NULL, farm=NULL, grade_quality='SS', grade_classification='FC', grade_screen=NULL, grade_prep=NULL, grade_label='SS FC', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_7d11bddf8db2e72d';
UPDATE coffee_source SET country_of_origin='Colombia', region=NULL, process=NULL, farm=NULL, grade_quality='Excelso', grade_classification=NULL, grade_screen=NULL, grade_prep='EP', grade_label='Excelso EP', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_0a84d7ad205487c5';
UPDATE coffee_source SET country_of_origin='Colombia', region='Huila', process=NULL, farm=NULL, grade_quality='Supremo', grade_classification=NULL, grade_screen=NULL, grade_prep='EP', grade_label='Supremo EP', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_e59e36a550ac6cfe';
UPDATE coffee_source SET country_of_origin='Colombia', region='Medellín', process=NULL, farm=NULL, grade_quality='Excelso', grade_classification=NULL, grade_screen=NULL, grade_prep='EP', grade_label='Excelso EP', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_a62b479c16f3a46f';
UPDATE coffee_source SET country_of_origin='Colombia', region=NULL, process=NULL, farm=NULL, grade_quality='Supremo', grade_classification=NULL, grade_screen=NULL, grade_prep='EP', grade_label='Supremo EP', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_1619c377f98171c9';
UPDATE coffee_source SET country_of_origin='Colombia', region=NULL, process=NULL, farm=NULL, grade_quality='Excelso', grade_classification=NULL, grade_screen=NULL, grade_prep='EP', grade_label='Excelso EP', is_peaberry=false, certifications='{}', varietals='{"Gesha"}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_241e8bed4968e9f0';
UPDATE coffee_source SET country_of_origin='Colombia', region=NULL, process=NULL, farm=NULL, grade_quality='Excelso', grade_classification=NULL, grade_screen=NULL, grade_prep='EP', grade_label='Excelso EP', is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_51dc895c7e973ba2';
UPDATE coffee_source SET country_of_origin='Costa Rica', region='Tarrazú', process=NULL, farm=NULL, grade_quality='SHB', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHB', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_c66f57af57b8205f';
UPDATE coffee_source SET country_of_origin='Brazil', region=NULL, process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_23753f1ab6d3f9c9';
UPDATE coffee_source SET country_of_origin='Colombia', region=NULL, process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_058f4808fbf5f03e';
UPDATE coffee_source SET country_of_origin='Mexico', region='Esmeralda', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_167feec140bf4ccc';
UPDATE coffee_source SET country_of_origin='Mexico', region=NULL, process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='798a628f-d9d0-42ea-ba65-77629775a8d3';
UPDATE coffee_source SET country_of_origin='El Salvador', region=NULL, process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_214aa09f8d6df8d9';
UPDATE coffee_source SET country_of_origin='El Salvador', region='Everest', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='15c8cf88-62f9-4dbf-8d3a-eae6854e1c14';
UPDATE coffee_source SET country_of_origin='Guatemala', region=NULL, process=NULL, farm=NULL, grade_quality='SHB', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHB', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='b33fe4ed-308f-4606-92ba-f5adc86284a1';
UPDATE coffee_source SET country_of_origin='Guatemala', region=NULL, process=NULL, farm=NULL, grade_quality='SHB', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHB', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_254a56c3c710f2c2';
UPDATE coffee_source SET country_of_origin='Honduras', region='Calán', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_f48911ac42eb8b84';
UPDATE coffee_source SET country_of_origin='Honduras', region='COMSA', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_2c416abfbff80f03';
UPDATE coffee_source SET country_of_origin='Honduras', region='Copán', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_548695e94eeac96e';
UPDATE coffee_source SET country_of_origin='Honduras', region='Siguatepeque', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_fec67ce029c1abd0';
UPDATE coffee_source SET country_of_origin='Honduras', region='COMSA', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_e58386e99c4408e6';
UPDATE coffee_source SET country_of_origin='Honduras', region='Copán', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_90760e479a2af138';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Ka''u', process=NULL, farm='Kau Coffee Mill', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-kau-coffee-mill', bag_size='100' WHERE coffee_source_id='csrc_419905aff309b85a';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Ka''u', process='Semi-Washed', farm='Kau Coffee Mill', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-kau-coffee-mill', bag_size='100' WHERE coffee_source_id='csrc_b12267adaddfb9fb';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Ka''u', process='Natural', farm='Kau Coffee Mill', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-kau-coffee-mill', bag_size='100' WHERE coffee_source_id='csrc_a110e005da5a37f0';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Ka''u', process='Honey', farm='Kau Coffee Mill', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-kau-coffee-mill', bag_size='100' WHERE coffee_source_id='csrc_c46a36549e65eff7';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Ka''u', process='Natural', farm='Kau Coffee Mill', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-kau-coffee-mill', bag_size='100' WHERE coffee_source_id='csrc_22b6cff651892be0';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Ka''u', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='aae70ef1-a9ce-4152-a760-aabeedfd8dba';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Ka''u', process='Honey', farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='4cb216bb-e7e2-4d87-bd69-9674ad39d908';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Ka''u', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='2d7716a7-bbc3-4dff-880c-df2679640626';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_54f520e29c3c78d2';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_3983ca85110c4fa5';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_3ee355aeaa090e0d';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm=NULL, grade_quality='H3', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='H3', is_peaberry=false, certifications='{}', varietals='{}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='4574235f-7e3a-4bf1-8560-0ce2619e748d';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality='H3', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='H3', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_b95b8329674802f0';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Farms', grade_quality='H3', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='H3', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-farms', bag_size='100' WHERE coffee_source_id='csrc_e912e88bdc7bb317';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_cd00fb0683a9171d';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='d439446a-6523-4365-b18b-3fc98fb48a57';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='b775e9c4-d9e9-4825-8c48-34901d3162b9';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_5b2aa7260e08ff80';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality='Prime', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Prime Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_e8146f2795c12d52';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Generations Kona', grade_quality='Prime', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Prime', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-generations-kona', bag_size='100' WHERE coffee_source_id='csrc_e9680b0b3ec3c1b2';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality='Prime', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Prime', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='cb3846a6-3119-47f4-b6d7-7fb65fd016a7';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality='Prime', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Prime', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_e2a2740c094d113c';
UPDATE coffee_source SET country_of_origin='USA – Hawaii (Big Island)', region='Kona', process=NULL, farm='Aloha Hills', grade_quality='Prime', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Prime', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-aloha-hills', bag_size='100' WHERE coffee_source_id='csrc_4952616625ead19a';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{"Mokka"}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='f47482ad-0c29-41e8-a85d-132cf6a61271';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{"Mokka"}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='b41d7af7-e06d-4ca5-87c8-6b3cc480ac40';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process='Natural', farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='csrc_0d41704569f55641';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Kona Coffee Company', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-kona-coffee-company', bag_size='100' WHERE coffee_source_id='csrc_05fece7c03fc47c7';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm=NULL, grade_quality='H3', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='H3', is_peaberry=false, certifications='{}', varietals='{}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='107396af-3b99-4c29-bf49-ecd6e8f05678';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Mahi Pono Farms', grade_quality='H3', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='H3', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='csrc_a6837a97a66e2a7e';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Mahi Pono Farms', grade_quality='H3', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='H3', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='csrc_e9a889b35f8b992e';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process='Natural', farm='Mahi Pono Farms', grade_quality='H3', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='H3', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='csrc_d793c3dba1f9c7d9';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Maui Grown Coffee', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{"Mokka"}', supplier_id='mcr-sup-maui-grown-coffee', bag_size='100' WHERE coffee_source_id='csrc_44109ca9903ae026';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{"Mokka"}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='csrc_487d98cba93b6956';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='csrc_8cac746b77fa5e30';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='csrc_bfd0fd07d8f36e9e';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Maui Grown Coffee', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-maui-grown-coffee', bag_size='100' WHERE coffee_source_id='csrc_ae0824323728699f';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process='Washed', farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{"Catuai"}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='csrc_0f87e935cf02c610';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process='Natural', farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100', is_active=false WHERE coffee_source_id='csrc_bc2db9e5c2d4507d';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process='Natural', farm='Maui Grown Coffee', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-maui-grown-coffee', bag_size='100' WHERE coffee_source_id='csrc_4e30e28a5edaac06';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='1386d9fe-da72-4469-8e95-64b170f7dd92';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='cbb0da10-c84a-4256-bcba-6834368bb32d';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id=NULL, bag_size='100' WHERE coffee_source_id='a1b7c502-64c5-4d6e-98a4-9d8745e40e1a';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process='Natural', farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100', is_active=false WHERE coffee_source_id='csrc_b30633e37f62d514';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Maui Grown Coffee', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-sup-maui-grown-coffee', bag_size='100' WHERE coffee_source_id='csrc_d11df67fcd1d3bd9';
UPDATE coffee_source SET country_of_origin='USA – Maui', region='Maui', process=NULL, farm='Mahi Pono Farms', grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-sup-mahi-pono-farms', bag_size='100' WHERE coffee_source_id='32eef649-9bb9-404e-b50d-e12dcbfa6691';
UPDATE coffee_source SET country_of_origin='Mexico', region=NULL, process=NULL, farm=NULL, grade_quality='HG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='HG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_42bc54fd2e84d170';
UPDATE coffee_source SET country_of_origin='Mexico', region=NULL, process=NULL, farm=NULL, grade_quality='HG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='HG', is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='64e874d8-6630-4516-9158-9fda9ad4b306';
UPDATE coffee_source SET country_of_origin='Mexico', region='Veracruz', process=NULL, farm=NULL, grade_quality='HG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='HG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_c8bfd38d18d2a86b';
UPDATE coffee_source SET country_of_origin='Mexico', region=NULL, process=NULL, farm=NULL, grade_quality='HG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='HG', is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_211af3db661e89ed';
UPDATE coffee_source SET country_of_origin='Mexico', region=NULL, process=NULL, farm=NULL, grade_quality='HG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='HG', is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_238de45a3dd9940b';
UPDATE coffee_source SET country_of_origin='Nicaragua', region='Segovia', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_c3d0eb4019e21b9b';
UPDATE coffee_source SET country_of_origin='Nicaragua', region='Olomega', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_7c9c7f0eca21d029';
UPDATE coffee_source SET country_of_origin='Nicaragua', region=NULL, process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{"Robusta"}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_0c03c745fe7bc804';
UPDATE coffee_source SET country_of_origin='Nicaragua', region='Olomega', process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='53b6f685-6a2f-4dcd-b9ad-732aac9fcb12';
UPDATE coffee_source SET country_of_origin='Nicaragua', region=NULL, process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{}', varietals='{"Robusta"}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='072387f0-483c-424c-8886-b0bdae097094';
UPDATE coffee_source SET country_of_origin='Nicaragua', region=NULL, process=NULL, farm=NULL, grade_quality='SHG', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='SHG', is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_10b5149aecee5e0d';
UPDATE coffee_source SET country_of_origin='Timor-Leste', region=NULL, process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_b505ba346aadb72d';
UPDATE coffee_source SET country_of_origin='Timor-Leste', region=NULL, process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_936ef021d0846852';
UPDATE coffee_source SET country_of_origin='Papua New Guinea', region='Papa', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_d2bed255e650be0e';
UPDATE coffee_source SET country_of_origin='Papua New Guinea', region=NULL, process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_b0855e2e4d4a11c5';
UPDATE coffee_source SET country_of_origin='Papua New Guinea', region='Papa', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_209100c254f6e64d';
UPDATE coffee_source SET country_of_origin='Papua New Guinea', region='Papa', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='39b0d699-07ce-4511-93a1-2d4427c31a4b';
UPDATE coffee_source SET country_of_origin='Papua New Guinea', region='Simbu', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_c9f7cf5ed2d057ae';
UPDATE coffee_source SET country_of_origin='Papua New Guinea', region='Papa', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_27019e3a8b1d2c6a';
UPDATE coffee_source SET country_of_origin='Papua New Guinea', region='Papa', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Peaberry', is_peaberry=true, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='80794daa-33d9-47f9-9ff5-cee88c3cb10e';
UPDATE coffee_source SET country_of_origin='Peru', region=NULL, process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_1483d3f39c6ded9f';
UPDATE coffee_source SET country_of_origin='Peru', region='Selva Andina', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{"Organic"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_c8a7362b8bc1d2fc';
UPDATE coffee_source SET country_of_origin='Peru', region=NULL, process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{"Organic","Fair Trade"}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_9e22c4ecd79db3bb';
UPDATE coffee_source SET country_of_origin='Peru', region='Vida Alta', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='154' WHERE coffee_source_id='csrc_c3692df4e5b76f59';
UPDATE coffee_source SET country_of_origin='Indonesia', region=NULL, process=NULL, farm=NULL, grade_quality='Grade 1', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Grade 1', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_ce35b4d21f498f12';
UPDATE coffee_source SET country_of_origin='Indonesia', region='Takengon', process=NULL, farm=NULL, grade_quality='Grade 1', grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label='Grade 1', is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='132' WHERE coffee_source_id='csrc_b39931a7edd8a6e3';
UPDATE coffee_source SET country_of_origin='Yemen', region='Mocca', process=NULL, farm=NULL, grade_quality=NULL, grade_classification=NULL, grade_screen=NULL, grade_prep=NULL, grade_label=NULL, is_peaberry=false, certifications='{}', varietals='{}', supplier_id='mcr-supplier-royal-coffee', bag_size='152' WHERE coffee_source_id='csrc_f9c78ea8c2cdba62';

-- 3. coffee_inventory group bag-size corrections (invoice truth)
UPDATE coffee_inventory SET bag_size='154' WHERE company_id='9ShiyDAXhV' AND origin='Colombia';  -- was 132
UPDATE coffee_inventory SET bag_size='132' WHERE company_id='9ShiyDAXhV' AND origin='Decaf';  -- was 152
UPDATE coffee_inventory SET bag_size='132' WHERE company_id='9ShiyDAXhV' AND origin='Pacific Peaberry';  -- was 152

COMMIT;
