-- Let a wholesale buyer save a card or a bank account for next time.
--
-- Activity Pay keep the instrument, in their Customer Vault. We keep the
-- pointer and enough to render a row a person recognises: "Visa ending 4242".
-- Nothing here is card data, and nothing here changes our PCI scope: the pan
-- goes from the buyer's browser into AP's hosted tokenizer and we are handed
-- a token, exactly as at checkout today.
--
-- ── Why the vault id is THEIRS and not ours ───────────────────────────────
--
-- AP's vault will accept a customer id we choose (2-40 characters of
-- a-zA-Z0-9._^-), which is tempting: both sides would say the same word for
-- the same buyer. It does not fit. customers.customer_id runs to 36
-- characters and company_id to 26, so the namespaced "company + customer" id
-- that a shared vault requires is 63 characters against a cap of 40.
--
-- And the vault IS shared. ACTIVITYPAY_SECRET_KEY is one key for the whole
-- platform, because STRATA is the merchant of record: there is one vault
-- behind it, holding every roaster's buyers together. Using a bare
-- customer_id would therefore have to be unique across all tenants, and the
-- short ones are eight hex characters. A collision would not be a failed
-- write, it would be one roaster's saved card attaching to another roaster's
-- customer record. That is not a risk worth taking to save a lookup.
--
-- So AP generate the ids and we store them. The row below is the map, and it
-- is company-scoped, which makes the invariant enforceable: the server
-- resolves a vault id FROM this table by (company_id, customer_id) taken from
-- the session. A vault id must never arrive from a request body.
--
-- ── Why a table and not two columns on customers ──────────────────────────
--
-- A buyer can reasonably keep a card and a bank account, or two cards on two
-- accounts payable. Columns would force one.

begin;

-- One vault customer per STRATA customer. AP hang payment methods off their
-- customer record, so this is the parent handle and it belongs on the parent.
alter table public.customers
  add column if not exists provider_vault_customer_id text;

comment on column public.customers.provider_vault_customer_id is
  'Activity Pay Customer Vault id for this customer. Generated by AP, stored here. Resolved server-side only, never accepted from a request.';

create table if not exists public.customer_payment_methods (
  payment_method_id          uuid primary key default gen_random_uuid(),
  company_id                 text not null references public.companies(company_id) on delete cascade,
  customer_id                text not null references public.customers(customer_id) on delete cascade,

  provider                   text not null default 'activitypay',
  -- Denormalised from customers.provider_vault_customer_id so a charge needs
  -- one read, not two. The unique constraint below is what keeps them honest.
  provider_vault_customer_id text not null,
  provider_payment_method_id text not null,

  method_type                text not null,
  -- What a person recognises. "Visa", "Mastercard", or the bank's name.
  display_brand              text,
  last4                      text,
  -- Cards only. A stored card that has expired can still be updated by AP's
  -- account updater, so these move.
  exp_month                  smallint,
  exp_year                   smallint,

  is_default                 boolean not null default false,
  -- Soft delete. A payment_transactions row points at the method that was
  -- charged; removing the row would orphan that history, and a buyer removing
  -- a card should not rewrite what was already taken from it.
  removed_at                 timestamptz,

  created_at                 timestamptz not null default now(),
  created_by                 text,
  updated_at                 timestamptz not null default now(),
  updated_by                 text,

  constraint customer_payment_methods_type_chk
    check (method_type in ('card', 'ach')),
  -- An expiry is a card fact. A bank account does not have one, and a card
  -- without one cannot be charged after AP's next update.
  constraint customer_payment_methods_card_expiry_chk
    check (method_type <> 'card' or (exp_month between 1 and 12 and exp_year >= 2000)),
  constraint customer_payment_methods_last4_chk
    check (last4 is null or last4 ~ '^[0-9]{4}$'),
  -- The same stored instrument must not be recorded twice for one customer.
  constraint customer_payment_methods_provider_unique
    unique (company_id, customer_id, provider, provider_payment_method_id)
);

-- The charge path reads by customer and wants only the live ones.
create index if not exists idx_customer_payment_methods_customer
  on public.customer_payment_methods (company_id, customer_id)
  where removed_at is null;

-- Exactly one default per customer, and only among live methods. A partial
-- unique index says that in a way application code cannot forget.
create unique index if not exists uq_customer_payment_methods_one_default
  on public.customer_payment_methods (company_id, customer_id)
  where is_default and removed_at is null;

comment on table public.customer_payment_methods is
  'Pointers to instruments stored in the payment provider vault. Holds no card or bank numbers: only the provider ids and the last four digits needed to render a recognisable row.';

alter table public.customer_payment_methods enable row level security;

create policy tenant_company_access on public.customer_payment_methods
  for all
  using (company_id in (select auth_company_ids()))
  with check (company_id in (select auth_company_ids()));

-- The buyer-facing storefront runs under the service role with explicit
-- company scoping on every query (app/(shop)/[slug]/**), the same as the rest
-- of the shop. RLS above is what protects the roaster-app side.

-- ── Permissions ───────────────────────────────────────────────────────────
-- Seeing and removing a customer's saved instruments is a roaster-side
-- action, so it needs its own key. It is plan gated on the same axis as the
-- rest of payments: a roaster who cannot take a card has nothing to save.

insert into public.permissions (permission_id, category, label, description, default_deny_message, is_plan_gated, sort_order)
values (
  'payment.saved_methods',
  'Payments',
  'Manage saved payment methods',
  'See the cards and bank accounts a customer has saved for future orders, and remove one on their behalf. Only the brand and last four digits are ever visible: the instrument itself stays with the payment processor.',
  'You do not have permission to manage saved payment methods.',
  true,
  84
)
on conflict (permission_id) do nothing;

insert into public.plan_permissions (plan_id, permission_id, granted, updated_reason)
values
  ('starter',         'payment.saved_methods', false, 'Saved payment methods follow card payments: Pro and above'),
  ('pro',             'payment.saved_methods', true,  'Saved payment methods follow card payments: Pro and above'),
  ('enterprise',      'payment.saved_methods', true,  'Saved payment methods follow card payments: Pro and above'),
  ('enterprise_plus', 'payment.saved_methods', true,  'Saved payment methods follow card payments: Pro and above')
on conflict (plan_id, permission_id) do update
  set granted = excluded.granted, updated_reason = excluded.updated_reason;

-- The same roles that hold payment.charge_card. Removing someone's saved card
-- is a lighter act than charging it, so this is deliberately not narrower.
insert into public.role_permissions (role_id, permission_id, granted)
select rp.role_id, 'payment.saved_methods', rp.granted
from public.role_permissions rp
where rp.permission_id = 'payment.charge_card'
on conflict (role_id, permission_id) do update set granted = excluded.granted;

do $probe$
begin
  if to_regclass('public.customer_payment_methods') is null then
    raise exception 'customer_payment_methods was not created';
  end if;
  if not exists (
    select 1 from public.permissions where permission_id = 'payment.saved_methods'
  ) then
    raise exception 'payment.saved_methods permission was not created';
  end if;
  -- A key nobody can hold is a key that denies everyone, silently.
  if not exists (
    select 1 from public.role_permissions
    where permission_id = 'payment.saved_methods' and granted
  ) then
    raise exception 'payment.saved_methods is granted to no role: it would deny every user';
  end if;
end
$probe$;

commit;
