-- Nothing without a person behind it may reprice a line that already exists.
--
-- Ten lines across six live MCR orders had a unit price sitting in
-- amount_override, which the engine reads as a line total -- $3,046.25 of
-- billing one edit away from becoming $539.31. The statement that did it ran
-- at 2026-08-31 10:15:34 HST across all six orders at once, left no
-- updated_by, is in no migration in this repo, and appears in no session
-- transcript on the machine. It cannot be named.
--
-- The owner's rule, and it is the right one: "no autogenerated script should
-- be able to adjust pricing after the order is input on an open order.
-- especially an override."
--
-- HOW THIS TELLS A SCRIPT FROM A PERSON. Every legitimate price edit goes
-- through a server action on createUserClient, which carries the operator's
-- JWT, so auth.uid() is set. A migration, a psql session or a service-role
-- script has no auth.uid(). That is the whole test, and it is the same signal
-- the NULL created_by/updated_by on those rows already gave.
--
-- WHAT IT GUARDS: the four columns that decide what a line costs, and only on
-- UPDATE. An INSERT is an order being entered; a migration still needs to be
-- able to write one. It is the silent restatement of a line somebody has
-- already agreed that must stop.
--
-- THE ESCAPE HATCH IS DELIBERATE AND LOUD. A migration that genuinely must
-- repair money says so:
--
--   set local app.allow_price_backfill = 'on';
--
-- which is one line, appears in the diff, and cannot be typed by accident.
-- 20260923000022 is exactly such a repair and carries it.
--
-- This does not fire on the engine's own work: handle_order_detail_logic is a
-- BEFORE trigger computing NEW, and this one runs BEFORE too but only refuses
-- when the values actually change AND there is no user AND no opt-in.

begin;

create or replace function public.guard_script_reprice()
returns trigger
language plpgsql
as $function$
begin
  -- A person is doing this: allowed, subject to the permission checks and the
  -- posted-invoice guards that already exist.
  if auth.uid() is not null then
    return NEW;
  end if;

  -- A migration that means it.
  if coalesce(current_setting('app.allow_price_backfill', true), '') = 'on' then
    return NEW;
  end if;

  if NEW.amount_override    is distinct from OLD.amount_override
     or NEW.unit_price_at_sale is distinct from OLD.unit_price_at_sale
     or NEW.list_price_total   is distinct from OLD.list_price_total
     or NEW.total_price        is distinct from OLD.total_price then
    raise exception
      'a script may not reprice line % of an existing order. If this is a deliberate repair, set local app.allow_price_backfill = ''on'' first.',
      OLD.order_detail_id;
  end if;

  return NEW;
end;
$function$;

-- Runs BEFORE handle_order_detail_logic so it judges what was ASKED for, not
-- what the engine derived. Trigger order within a timing class is alphabetical,
-- and 'aaa_' sorts ahead of 'trg_handle_order_details'.
drop trigger if exists aaa_guard_script_reprice on public.order_details;
create trigger aaa_guard_script_reprice
  before update on public.order_details
  for each row execute function public.guard_script_reprice();

do $$
declare
  v_id text;
  v_ok boolean := false;
begin
  if not exists (
    select 1 from pg_trigger
    where tgrelid = 'public.order_details'::regclass
      and tgname = 'aaa_guard_script_reprice'
  ) then
    raise exception 'the guard was not attached';
  end if;

  -- PROVE IT REFUSES. This session has no auth.uid(), so a bare price change
  -- must be rejected.
  select order_detail_id into v_id
  from public.order_details
  where total_price is not null limit 1;

  if v_id is not null then
    begin
      update public.order_details set total_price = total_price + 1 where order_detail_id = v_id;
      raise exception 'the guard did NOT refuse a scripted reprice';
    exception
      when sqlstate 'P0001' then
        if position('may not reprice' in sqlerrm) > 0 then
          v_ok := true;
        else
          raise;
        end if;
    end;

    if not v_ok then
      raise exception 'the guard refused for the wrong reason';
    end if;
    raise notice 'guard proven: a scripted reprice was refused';
  end if;
end $$;

commit;
